### ISSUE TITLE
Issue compiling annotations

### ISSUE THREAD

**Issue by srskc** [janino-compiler/janino#36] opened 2017-12-22 14:33 UTC
I'm on 3.0.8. Compiling a small JPA class file with three annotations fails:

```
	@Id
	@GeneratedValue(strategy=IDENTITY)
	@Column(nullable=false)
	private java.lang.Integer id;

```

If I remove the `@GeneratedValue` annotation, everything works fine.

The input code compiles with JDK7-8.

Error:

```
Exception in thread "main" java.lang.StackOverflowError
	at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8222)
	at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8119)
	at org.codehaus.janino.UnitCompiler.reclassify(UnitCompiler.java:7986)
	at org.codehaus.janino.UnitCompiler.access$1000(UnitCompiler.java:212)
	at org.codehaus.janino.UnitCompiler$22$2.visitRvalue(UnitCompiler.java:8058)
	at org.codehaus.janino.Java$Rvalue.accept(Java.java:3855)
	at org.codehaus.janino.UnitCompiler$22.toObject(UnitCompiler.java:8051)
	at org.codehaus.janino.UnitCompiler$22.toIAnnotation(UnitCompiler.java:8027)
	at org.codehaus.janino.UnitCompiler$22.visitNormalAnnotation(UnitCompiler.java:8019)
	at org.codehaus.janino.UnitCompiler$22.visitNormalAnnotation(UnitCompiler.java:8002)
	at org.codehaus.janino.Java$NormalAnnotation.accept(Java.java:477)
	at org.codehaus.janino.UnitCompiler.toIAnnotation(UnitCompiler.java:8001)
	at org.codehaus.janino.UnitCompiler.toIAnnotations(UnitCompiler.java:7993)
	at org.codehaus.janino.UnitCompiler.compileField(UnitCompiler.java:7895)
	at org.codehaus.janino.UnitCompiler.compileFields(UnitCompiler.java:7860)
	at org.codehaus.janino.UnitCompiler.access$17600(UnitCompiler.java:212)
	at org.codehaus.janino.UnitCompiler$30.getDeclaredIFields2(UnitCompiler.java:9532)
	at org.codehaus.janino.IClass.getDeclaredIFieldsCache(IClass.java:345)
	at org.codehaus.janino.IClass.getDeclaredIField(IClass.java:358)
	at org.codehaus.janino.UnitCompiler.findIField(UnitCompiler.java:11725)
	at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8321)
	at org.codehaus.janino.UnitCompiler.reclassifyName(UnitCompiler.java:8119)
	at org.codehaus.janino.UnitCompiler.reclassify(UnitCompiler.java:7986)
	at org.codehaus.janino.UnitCompiler.access$1000(UnitCompiler.java:212)
	at org.codehaus.janino.UnitCompiler$22$2.visitRvalue(UnitCompiler.java:8058)
	at org.codehaus.janino.Java$Rvalue.accept(Java.java:3855)
	at org.codehaus.janino.UnitCompiler$22.toObject(UnitCompiler.java:8051)
	at org.codehaus.janino.UnitCompiler$22.toIAnnotation(UnitCompiler.java:8027)
	at org.codehaus.janino.UnitCompiler$22.visitNormalAnnotation(UnitCompiler.java:8019)
	at org.codehaus.janino.UnitCompiler$22.visitNormalAnnotation(UnitCompiler.java:8002)
	at org.codehaus.janino.Java$NormalAnnotation.accept(Java.java:477)
 . . .
```

Another question: Are there any build instructions for Janino and the commons-compiler jars?

**Comment by oontvoo** [comment] 2017-12-27 08:24
Hi,

Would you be able to provide a full repro case? (a standalone .java file would be great).

As for building janino, these are just maven projects. You can cd into the interested dir and do "mvn clean install".

Cheers,

Vy

**Comment by aunkrig** [comment] 2017-12-27 13:15
This problem is probably the same as pull request #31, which I just merged. Please update to HEAD and re-test if the problem is fixed.

**Comment by aunkrig** [comment] 2018-01-09 11:18
> Another question: Are there any build instructions for Janino and the commons-compiler jars?

Well, it's a normal MAVEN project, so check out projects "janino" and "commons-compiler", and run "mvn install".

**Comment by aunkrig** [comment] 2018-02-21 13:48
AYT?

**Closed** 2018-08-28 08:57 UTC
