### ISSUE TITLE
Java 9/10 commons.compiler.jdk Support

### ISSUE THREAD

**Issue by gchallen** [janino-compiler/janino#51] opened 2018-07-11 20:45 UTC
I just discovered Janino's ability to use the built-in `javax.tools` compiler. You have no idea how much time that has saved me—thanks so much for that. (And of course it exposes how much faster Janino is... wow.)

Are there plans to get this working with more recent versions of Java: 9 or 10? Note that I don't mean adding support for these new features to Janino's compiler—I understand how much work that would be. Hopefully supporting the javax.tools compiler would be simpler.

I accidentally experimented with this today as I had my IntelliJ configured to use Java 9. So I can confirm that it does not work. But the problem looked like it was asking the `SimpleCompiler` class whether a given option was supported which triggered an exception that caused everything to fail. I can reproduce with more details if it's helpful. But I was wondering if just ignoring that option request or returning `false` would allow things to move forward.

Anyway, thanks again for all of your hard work on this project. I have an unrelated question that I'll open separately.

**Comment by aunkrig** [comment] 2018-08-28 05:35
Hey Geoffrey,

yes, I once tried to make `commons.compiler.jdk` work with JDK 9+, but wasn't successful... the `javax.compiler` API is really weird. It was a trial-and-error job to get it working for pre-Java 9 JDK.

Alas, that is a strong argument for doing it, to save users to go through that vale of tears 😉.

If you were motivated to dig into this, then I'd be deeply grateful. I presume that it's only a few lines of code, but a lot of experimenting...


CU Arno

**Comment by aunkrig** [comment] 2018-11-12 20:41
> I found the problem and fixed it... please test! The regression suite now runs successfully for JDK 9+, exception for the org.codehaus.commons.compiler.jdk.JavaSourceClassLoader.

Now that bug is fixed as well, and `commons-compiler-jdk` is now fully functional for all JDK versions!

Please test!

**Comment by Bio7** [comment] 2018-11-21 12:12
First of all thank you very much for making this API and package available. I use it since several years (2005) in my RCP application to compile files (in the beginning) and packages on the fly and in the current Java process and it works simply great in comparison with other solutions.

I totally agree on some opinons here that the compiler API is unnecessary complex.

I had the same problem with the JavaSourceClassLoader and OpenJDK 11 which I use directly in my application to compile Java class(es) dynamically. However after a great amount of time I was able to workaround the problem by compiling the files to classfiles (instead of using the ByteArrayJavaFileManager) which fits perfectly in my setup, here the changes I made to the JavaSourceClasLoader class where I define the source and binary path for a standard file manager:

```java
JavaFileManager getJavaFileManager() {
		if (this.fileManager == null) {

			
			StandardJavaFileManager jfm = this.compiler.getStandardFileManager(null, null, null);
			ArrayList ar=new ArrayList();
			for (int i = 0; i < sourcePath.length; i++) {
				ar.add(this.sourcePath[i]);
			}
			
			ArrayList arout=new ArrayList();
			for (int i = 0; i < binaryPath.length; i++) {
				arout.add(this.binaryPath[i]);
			}
		    try {
		    	
				jfm.setLocation(StandardLocation.SOURCE_PATH,ar);
			
				jfm.setLocation(StandardLocation.CLASS_OUTPUT,arout);
			} catch (IOException e) {
			
				e.printStackTrace();
			}

			this.fileManager = jfm;
		}
		return this.fileManager;
	}
```
This works fine in OpenJDK 11 also for a temp. location. Before I compile the files I delete  the *.class files so that the are loaded instead of the old comiled classes if available (at the moment a complete Eclipse Java project in a bin folder).

One nice side effect of this is that I can load already compiled class files in a special plugin location.

With the current version of the commons compiler I still get this typical package clash errors:

```
Error on line -1 -> module javafx.swing reads package  from both java.base and java.naming

*** error: module javafx.swing reads package  from both java.base and java.naming *** compiler.err.package.clash.from.requires
Error on line -1 -> module javafx.swing reads package  from both java.base and jdk.internal.vm.ci

*** error: module javafx.swing reads package  from both java.base and jdk.internal.vm.ci *** compiler.err.package.clash.from.requires
Error on line -1 -> module javafx.swing reads package  from both java.base and java.sql..........
.......................................
```
It might be that this is a special error because i use the compiler API inside of an Eclipse RCP application.

**Comment by gchallen** [comment] 2018-11-21 14:14
This is working beautifully, thanks! Both Java 9 and Java 10 features are now working in my JDK fallback.

Thanks again to @aunkrig for all of your hard work on this project. Fantastic stuff.

**Comment by aunkrig** [comment] 2018-11-21 14:14
That exception „reads package from both...“ is probably not related to RCP. I‘ve had the same problem and fixed it on Nov 13. Basically the trick is to use the „FowardingJavaFileManager“.

**Comment by Bio7** [comment] 2018-11-21 14:43
One question for my understanding.
Where or how do I have to use the FowardingJavaFileManager in the getJavaFileManager method (using the JavaSourceClassLoader) ?

**Comment by aunkrig** [comment] 2018-11-22 05:36
@bio7: I mean I solved the same problem that you report by using the `ForwardingJavaFileManager` in the JSCL, so you may want to look at the Nov 13 code changes and adapt them for for *your* code.

**Comment by Bio7** [comment] 2018-11-22 11:55
@aunkrig I can't find a reference of ForwardingJavaFileManager in the JSCL:
https://github.com/janino-compiler/janino/blob/master/commons-compiler-jdk/src/main/java/org/codehaus/commons/compiler/jdk/JavaSourceClassLoader.java

Is it already committed?

**Comment by aunkrig** [comment] 2018-11-27 13:11
Sorry, typo: I mean
```
/commons-compiler-jdk/src/main/java/org/codehaus/commons/compiler/jdk/SimpleCompiler.java
```
, commit on 11/9 15:53:

```java
        final JavaFileManager
        fileManager = new ForwardingJavaFileManager<JavaFileManager>(
            ToolProvider
            .getSystemJavaCompiler()
            .getStandardFileManager(dl, Locale.US, Charset.forName("UTF-8"))
        ) {
        ...
```

**Comment by aunkrig** [comment] 2018-12-05 08:54
Any questions left?

**Comment by Bio7** [comment] 2018-12-05 13:43
Thanks for the hint. 

But I use JavaSourceClassLoader class directly and still get the same error. 

However the getJavaFileManager() method in my first post works fine (creating a *.class file).

So how do I have to change the getJavaFileManager() method?

**Comment by aunkrig** [comment] 2019-01-09 02:14
Ping.

**Comment by aunkrig** [comment] 2019-01-18 11:52
Ping.

**Comment by aunkrig** [comment] 2019-01-25 20:22
Ping.

**Comment by Bio7** [comment] 2019-02-01 09:54
@aunkrig again sorry for the late reply. I have to popstpone a test case because I'm currently very busy to fix very annoying bugs of my application which eats up all free time I have.
After my next application release I will try to create a reproducible example.

**Comment by aunkrig** [comment] 2019-02-01 11:15
No problem!

**Closed** 2019-06-25 18:49 UTC
