### ISSUE TITLE
Turning logging off by default

### ISSUE THREAD

**Issue by sertel** [janino-compiler/janino#12] opened 2016-12-16 08:29 UTC
Hi,

The following exception is printed to the console when I execute a simple evaluation:

```
java.lang.ClassNotFoundException: de.unkrig.jdisasm.Disassembler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.codehaus.janino.UnitCompiler.disassembleToStdout(UnitCompiler.java:11913)
	at org.codehaus.janino.UnitCompiler.addClassFile(UnitCompiler.java:847)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:841)
	at org.codehaus.janino.UnitCompiler.compile2(UnitCompiler.java:431)
	at org.codehaus.janino.UnitCompiler.access$400(UnitCompiler.java:209)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:385)
	at org.codehaus.janino.UnitCompiler$2.visitPackageMemberClassDeclaration(UnitCompiler.java:380)
	at org.codehaus.janino.Java$PackageMemberClassDeclaration.accept(Java.java:1405)
	at org.codehaus.janino.UnitCompiler.compile(UnitCompiler.java:380)
	at org.codehaus.janino.UnitCompiler.compileUnit(UnitCompiler.java:354)
	at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:413)
	at org.codehaus.janino.ClassBodyEvaluator.compileToClass(ClassBodyEvaluator.java:318)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:597)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:489)
	at org.codehaus.janino.ScriptEvaluator.cook(ScriptEvaluator.java:422)
	at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:200)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:76)
	at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:71)
	at com.ohua.engine.flowgraph.elements.operator.CallArrayConstruction$C
```
The code is not failing but I don't want this log output. It seems that the logger is per-default set to log level FINEST. Is that necessary?

**Comment by aunkrig** [comment] 2017-01-11 13:59
Duplicate of #13

**Closed by aunkrig** 2017-01-11 13:59 UTC
